version: '3'
services:
    mongodb:
        image: mongo:latest
        restart: always
        volumes:
            - ./mongodb:/data/db

    pritunl:
        # Use the following to build the image from source.
        build:
            context: .
        restart: always
        depends_on:
            - mongodb
        privileged: true
        networks:
            - nginx
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=0
        links:
            - mongodb
        volumes:
            - /etc/localtime:/etc/localtime:ro
        ports:
            # The following are the two default ports for the tcp+udp servers (you may edit these as needed!)
            - 1194:1194
            - 1194:1194/udp
            - 8080:8080
            - 8080:8080/udp
        environment:
            - TZ=UTC
            - MONGODB_URI=mongodb://mongodb:27017/pritunl
            # Also enable reverse proxie capabilities
            - REVERSE_PROXY=true
networks:
  nginx:
    external:
      name: nginx_default
